object Compose {
    const val snapshot = ""
    const val version = "0.18.0"

    const val foundation = "androidx.compose.foundation:foundation:${Versions.compose}"
    const val layout = "androidx.compose.foundation:foundation-layout:${Versions.compose}"
    const val ui = "androidx.compose.ui:ui:${Versions.compose}"
    const val uiUtil = "androidx.compose.ui:ui-util:${Versions.compose}"
    const val runtime = "androidx.compose.runtime:runtime:${Versions.compose}"
    const val runtimeLiveData = "androidx.compose.runtime:runtime-livedata:${Versions.compose}"
    const val material = "androidx.compose.material:material:${Versions.compose}"
    const val animation = "androidx.compose.animation:animation:${Versions.compose}"
    const val tooling = "androidx.compose.ui:ui-tooling:${Versions.compose}"
    const val iconsExtended = "androidx.compose.material:material-icons-extended:${Versions.compose}"
    const val activityCompose = "androidx.activity:activity-compose:${Versions.compose}"
    const val viewModelCompose = "androidx.lifecycle:lifecycle-viewmodel-compose:${Versions.viewModelCompose}"
    const val navigationCompose = "androidx.navigation:navigation-compose:${Versions.navigationCompose}"
    const val constraintCompose = "androidx.constraintlayout:constraintlayout-compose:${Versions.constraintCompose}"
    const val coilCompose = "io.coil-kt:coil-compose:${Versions.coilCompose}"
    const val uiTest = "androidx.compose.ui:ui-test-junit4:${Versions.compose}"
    const val splashScreen = "androidx.core:core-splashscreen:${Versions.splashScreen}"
}